### ISSUE TITLE
Including newcommands in dropdown

### ISSUE THREAD

**Issue by diego898** [r-stein/st-latex-prefix-key#2]
Firstly, thank you for this plugin! I think this is great! I have thought it would be nice to have a plugin like this to help you insert your own `newcommands` that you might have created either in the current file, the `root` file declared at the top of the current file, or any other imported/included files found along the way.

Do you think it would be difficult to do building on the work done in this plugin? I've never made a sublime plugin before.

Thanks!

**Comment by r-stein** [comment]
Do you mean autocompletion of the commands?

**Comment by diego898** [comment]
both autocompletion and then being shown in the overview

**Comment by r-stein** [comment]
`Ctrl+r` overview?

**Comment by diego898** [comment]
Your statement: "You can press the prefix key followed by ? to get an overview over all available commands in the prefix keymap:"

My idea: also include "newcommands" in that dropdown

**Comment by r-stein** [comment]
If you install https://packagecontrol.io/packages/LaTeX-cwl LaTeXTools will have cwl completion (https://github.com/SublimeText/LaTeXTools/pull/504) and completion of your defined commands (https://github.com/SublimeText/LaTeXTools/pull/711).

![example](https://cloud.githubusercontent.com/assets/12573621/11513807/7aecc68c-9875-11e5-89ce-7c002103dba0.gif)

So you have added those commands to the autocompletion popup, which is automatically triggered when you press `\`. If I undestand you correct this is nearly what you requested.

**Comment by diego898** [comment]
indeed, but that popup is populated with many many more items! I just thought it would be nice to have a popup specifically for commands that I have defined

**Comment by r-stein** [comment]
Ah okay I am not sure how many people actually want this, but if you have LaTeXTools installed it is pretty easy to achive.
Just select `Tools >> Developer >> New Plugin...` and paste (and save):

``` py
import sublime_plugin

from LaTeXTools.latex_own_command_completions import get_own_command_completion


class OwnCompletionPopupCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        view = self.view
        window = view.window()
        comp = get_own_command_completion(view)

        items = [c[0].split("\t")[0] for c in comp]

        def on_select(index):
            if index < 0:
                return
            view.run_command(
                "insert_snippet", {"contents": "\\" + comp[index][1]})
        window.show_quick_panel(items, on_select=on_select)
```

Afterwards open your keymap and add a keybinding:

``` js
    {
        "keys": [";"],
        "command": "own_completion_popup",
        "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.tex.latex - meta.environment.math" }
        ]
    },

    {
        // you still can insert ;
        "keys": ["ctrl+l", ";"],
        "command": "insert",
        "args": {"characters": ";"},
        "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }
        ]
    },
```

**Comment by diego898** [comment]
Wow! This is great! Thank you for this starting point! You're right, not sure how many would like this, but I can use this a starting point! I'll go about adding: 
- removing the included `{}` at the end of commands with no arguments
- adding any comments to the right of the command (for context)
- separating the list into files where the command was originally defined
- Adding a `command+enter` to take you to the definition instead of inserting it. 

Thanks so much for your help in getting me started!

**Comment by r-stein** [comment]
For the navigation point and maybe also the other ones you may be interested in this PR https://github.com/SublimeText/LaTeXTools/pull/781, which will be included in the next LaTeXTools update.

**Comment by diego898** [comment]
wow! thats great thanks for pointing that out! Im looking forward to those features as well as a readme update!
